apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-server-deployment
  namespace: lge-ebme
  labels:
    app: fl-server
  annotations:
    kubernetes.io/change-cause: "Init deployment"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: fl-server
  template:
    metadata:
      labels:
        app: fl-server
    spec:
      restartPolicy: Always
      containers:
        - name: fl-server
          image: lgecloudroboticstask/fl:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["python server.py"]
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 8000m
              memory: 16Gi
          volumeMounts:
            - mountPath: /mnt/checkpoints
              name: checkpoints
      volumes:
        - name: checkpoints
          persistentVolumeClaim:
            claimName: fl-checkpoints-pvc
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: kube-cluster-worker1
