apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-1-deployment
  namespace: lge-ebme
  labels:
    app: fl-client-1
  annotations:
    kubernetes.io/change-cause: "Init deployment"
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: fl-client-1
  template:
    metadata:
      labels:
        app: fl-client-1
    spec:
      containers:
        - name: fl-client-1
          image: lgecloudroboticstask/fl:latest
          imagePullPolicy: Always
          command: ["/bin/bash", "-c"]
          args: ["python flower_obj/client.py"]
          env:
            - name: SERVER_IP
              value: "10.177.196.41"
            - name: SERVER_PORT
              value: "30180"
          resources:
            requests:
              cpu: 1000m
              memory: 512Mi
            limits:
              cpu: 8000m
              memory: 16Gi
          volumeMounts:
            - mountPath: /mnt/checkpoints
              name: checkpoints
      volumes:
        - name: checkpoints
          persistentVolumeClaim:
            claimName: fl-checkpoints-pvc
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        kubernetes.io/hostname: kube-cluster-worker3
